general:
  basemodel: "rinna/japanese-gpt2-xsmall"
dataset:
  input_path: "/content/gdrive/MyDrive/data/chat_history_cleaned.pk"
  output_path: "gpt2_train_data.txt"
train:
  epoch: 10
  save_steps: 10000
  save_total_lime: 3
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  output_dir: "model/default"
  use_fast_tokenizer: False